### PR TITLE
MINOR Include a screenshot that will show up in addons site

### PR DESCRIPTION
**Pull request by camfindlay**
When in "app" view in addons.silverstripe.org the screenshot gets shown.

### CODE REVIEW

**Comment by nglasl** [comment]
Hi @camfindlay, is this the "app" view and should the image be displaying now?

http://addons.silverstripe.org/add-ons?sort=newest&view=expanded

**Comment by camfindlay** [comment]
Yes, and it will take time to show up, addons indexes packagist nightly I think.

**Comment by nglasl** [comment]
No worries, will keep an eye on it. Thanks for the PR :)

**Comment by nglasl** [comment]
It looks like there's some trouble parsing the image, @camfindlay. The image looks to have been pulled in correctly, however there's a 404 when trying to access the cropped version.

**Comment by camfindlay** [comment]
Thanks @nglasl will look into it. Seems it has at least pulled the correct image over to the site which is a good start.

**Pull request merged**
